jobs:

- job: Ubuntu

  pool:
    vmImage: 'Ubuntu 16.04' # 'VS2017-Win2016'

  variables: 
     solution: '**/*.sln' 
     buildPlatform: 'Any CPU' 
     buildConfiguration: 'Release' 

  steps:
 
  # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
  - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql:5.7 
    displayName: 'Run MySql on Linux container'
    
  - script: echo "##vso[task.setvariable variable=mySQLIP;isOutput=true]$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" mysql)"
    name: setvarStep
    displayName: '[obsolete] Get Ip from MySql container'

  - script: docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password12!' -p 1433:1433  -d microsoft/mssql-server-linux:2017-latest
    displayName: 'Run SQL 2017 on Linux container'

  #- script: |
  #    sqlcmd -S localhost -U sa -P 'Password12!' -Q 'select @@VERSION'
  #    exit
  #  continueOnError: 'true'
  #  displayName: 'Run SQLCMD, Continue if any error'

  - script: dotnet build Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj
    displayName: 'Dotmim.Sync.Core'
  - script: dotnet build Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj
    displayName: 'Dotmim.Sync.SqlServer'
  - script: dotnet build Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj
    displayName: 'Dotmim.Sync.Sqlite'
  - script: dotnet build Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj
    displayName: 'Dotmim.Sync.MySql'
  - script: dotnet build Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj
    displayName: 'Dotmim.Sync.Web.Client'
 
  # Because we have a build on both .Net Standard 2.0 AND .Net 4.6, We just make the build on .Net Standard 2.0
  - script: dotnet build Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj -f netstandard2.0
    displayName: 'Build Dotmim.Sync.Web.Server for .Net Standard 2.0' 
  
  - script: dotnet build Projects/dotnet-sync/dotnet-sync.csproj
    displayName: 'dotnet-sync'

  # Dont need anymore to pass the MySQL Ip Address, just let it here for memory
  # --logger trx;logfilename=TEST.xml : Unexplained arg to publish tests resuls
  - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --logger trx;logfilename=TEST.xml
    displayName: 'Tests'
    env: 
      'MYSQLIP' : $(setvarStep.mySQLIP)
      'AZUREDEV' : 'true'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
